name: Deploy to AWS

on:
  workflow_dispatch: 

permissions:
  id-token: write   # Required to request the OIDC JWT token from GitHub
  contents: read    # Required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::781978598522:role/GitHubRole
          aws-region: eu-west-1

      - name: Print AWS Account Buckets
        run: aws s3 ls
