on:
  workflow_dispatch:


jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: Mask custom value
        run: echo "::add-mask::my-secret"
      - name: Anything
        run: echo "my-secret"
