on:
  workflow_dispatch:


jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: Mask secret
        shell: bash {0}
        run: echo "::add-mask::my-secret" >/dev/null
      - name: Anything
        run: echo "my-secret"
